In [33]:
import numpy as np
import random
import pickle

In [34]:
file_n = '/home/xw17070/Documents/bin-packing-r2/xw_mcts/temp/rewards_list_10_items.pkl'
with open(file_n, "rb") as input_file:
    rewards_list = pickle.load(input_file)

In [35]:
len(rewards_list)

100

In [36]:
min(rewards_list)

0.8264462809917356

In [37]:
max(rewards_list)

1.0

In [38]:
sum([j == max(rewards_list) for j in rewards_list])

23

In [12]:
np.random.seed()
np.random.randint(int(1e5))

58782

In [25]:
valids = [0] * 10

In [26]:
valids

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [27]:
valids[-2:] = [1,1]

In [28]:
valids

[0, 0, 0, 0, 0, 0, 0, 0, 1, 1]

In [30]:
np.concatenate([valids,[3,3]])

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 3, 3])

In [58]:
random.seed(1)
b = random.sample(range(10, 100), 5)
print(b)
np.random.choice(b)

[27, 82, 18, 42, 25]


25

In [35]:
item_list = [[20,20,0,0]]

In [37]:
item_list.extend([1,1,1,1],[3,3,3,3])

TypeError: extend() takes exactly one argument (2 given)

In [21]:
item_list

[[20, 20, 0, 0], [1, 1, 1, 1]]

In [32]:
[w, h, a, b] = item_list[0]

In [33]:
w

20

In [34]:
a

0

In [38]:
for i in range(3):
    print(i)

0
1
2


In [39]:
a = [1,2,3]

In [41]:
a[:-1]

[1, 2]

In [42]:
a[1:2]

[2]

In [43]:
a[0:2]

[1, 2]

In [47]:
a = [1, 2, 5, 3, 4]

In [50]:
b = np.sort(a)

In [51]:
b

array([1, 2, 3, 4, 5])

In [49]:
a

[1, 2, 5, 3, 4]

In [53]:
len(b) * 0.75

3.75

In [61]:
np.random.choice([1, -1], p=[0.5, 0.5])

1

In [113]:
a = np.zeros((2,3))

In [114]:
a[0][0:2] = 2

In [115]:
a

array([[2., 2., 0.],
       [0., 0., 0.]])

In [118]:
sum(a[0,:])

4.0

In [117]:
sum(a[:,0])

2.0

In [103]:
a[1][1] = 1

In [94]:
a

array([[0., 0., 0.],
       [0., 1., 0.]])

In [100]:
a[0:1]

array([[0., 0., 0.]])

In [71]:
b = a.tostring()

In [75]:
c = b + b

In [77]:
len(c)

96

In [78]:
sum(b,b)

TypeError: sum() can't sum bytes [use b''.join(seq) instead]

In [89]:
d = np.array([]).tostring()

In [92]:
e = d + b

In [93]:
len(e)

48

In [86]:
type(b)

bytes

In [119]:
a = [1, 2, 3]

In [120]:
list(a)

[1, 2, 3]

In [112]:
a[1:]

[2, 3]